### ISSUE TITLE
Whitelist not working.

### ISSUE THREAD

**Issue by Boy17000** [BlackDemonZyT/BotSentry#107]
Evening doing the whitelist command does not seem to add it into the yml file...
it says ingame that it did but it didnt. also got some console errors:

[13:57:01 WARN]: java.io.IOException
[13:57:01 WARN]:        at BotSentry-9.5.3-THANATOS.jar//com.lahuca.botsentry.d.m.c(Unknown Source)
[13:57:01 WARN]:        at BotSentry-9.5.3-THANATOS.jar//com.lahuca.botsentry.b.b.b.a(Unknown Source)
[13:57:01 WARN]:        at BotSentry-9.5.3-THANATOS.jar//com.lahuca.botsentry.b.b.d.run(Unknown Source)
[13:57:01 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:57:01 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:57:01 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:57:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:57:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:57:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Laurenshup** [comment]
Hi @Boy17000, this problem seems to be solvable by giving some more personal information. I would like to request that you make a ticket and provide the following details: server IP and licence ID (Spigot/BuiltByBit Profile ID). I will help you there solve this problem.

**Comment by Laurenshup** [comment]
Hi @Boy17000, did you reach contact with us?

**Comment by Laurenshup** [comment]
Invalid due to inactivity.
