### ISSUE TITLE
Error on Velocity  newest versions, botsentry wont load

### ISSUE THREAD

**Issue by BlackDemonZyT** [BlackDemonZyT/BotSentry#23]
[19:25:49 ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[19:25:49 ERROR]: #1:

java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
        at com.lahuca.botsentry.velocity.BotSentryVelocity.a(Unknown Source) ~[?:?]
        at net.kyori.event.asm.generated.7465968cbc.BotSentryVelocity-a-ProxyInitializeEvent-1.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[VentryCord.jar:1.0.11-SNAPSHOT (git-b14e7e65-b247)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[VentryCord.jar:1.0.11-SNAPSHOT (git-b14e7e65-b247)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:136) ~[VentryCord.jar:1.0.11-SNAPSHOT (git-b14e7e65-b247)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$0(VelocityEventManager.java:117) ~[VentryCord.jar:1.0.11-SNAPSHOT (git-b14e7e65-b247)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66) ~[VentryCord.jar:1.0.11-SNAPSHOT (git-b14e7e65-b247)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43) ~[VentryCord.jar:1.0.11-SNAPSHOT (git-b14e7e65-b247)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_261]
        ... 9 more

**Comment by Laurenshup** [comment]
I cannot reproduce this issue. I have downloaded the newest version of Velocity (1.1.5) and installed BotSentry on there. I do not receive any errors. What did you do to receive this error?

**Comment by Laurenshup** [comment]
I did run commands. Works flawlessly. It just does not make any sense, those classes should be loaded. Probably wrong JAR download.

**Comment by Laurenshup** [comment]
Cannot reproduce.
