### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by KasprTv** [BlackDemonZyT/BotSentry#40]
[13:37:38 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@14bf57b2, id=50756, owner=com.lahuca.botsentry.bungee.BotSentryBungee@b071526, task=com.lahuca.botsentry.d.i$$Lambda$836/0x0000000100783dc8@51523194, delay=0, period=0, running=true) encountered an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1584) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1607) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap$KeySetView.addAll(ConcurrentHashMap.java:4671) ~[?:?]
        at com.lahuca.botsentry.d.i.f(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.d.i.h(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.d.d.h(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.d.d.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.d.i.c(Unknown Source) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[server.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Laurenshup** [comment]
Looks like this is very similar to #37. Setting this to closed.
