### ISSUE TITLE
Error in console reported via Discord Support

### ISSUE THREAD

**Issue by Laurenshup** [BlackDemonZyT/BotSentry#5]
Reported via Discord Support

Reported by: @R'Goth#2653

[16:49:54 ERROR]: Exception in task com.lahuca.botsentry.d.h$$Lambda$767/0x000000084038bc40@17af3024 by plugin BotSentry
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
        at java.util.AbstractCollection.addAll(AbstractCollection.java:351) ~[?:?]
        at java.util.HashSet.<init>(HashSet.java:120) ~[?:?]
        at com.lahuca.botsentry.d.h.c(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.d.j.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.d.h.b(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:203) ~[ElementaryProxy.jar:1.1.5-SNAPSHOT (git-5ea6728d-bunknown)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Laurenshup** [comment]
Server Software: Velocity

Notes: Java 8 (Being that velocity runs on Java 11)

**Comment by Laurenshup** [comment]
.After more investigation. I have concluded that I already fixed an issue related to this in the code on February 8th. This bug will be fixed in the upcoming update.
