### ISSUE TITLE
NullPointerException when antiProxy.json is empty

### ISSUE THREAD

**Issue by Dacaly** [BlackDemonZyT/BotSentry#60]
Hi, so when I use BotSentry-9.2 with Waterfall 1.18, this error shows up. I'm not sure, but Geyser might have something to do with it, since only when a Geyser-player joins, the error prints.

```
[05:10:57 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@28c88600, id=1948, owner=com.lahuca.botsentry.bungee.BotSentryBungee@450c57b3, task=com.lahuca.botsentry.b.b.d@4a8273ad, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "<local2>" is null
        at com.lahuca.botsentry.b.a.d.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.b.a.d.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.b.a.d.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.d.b.c.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.d.b.c.a(Unknown Source) ~[?:?]
        at com.lahuca.botsentry.b.b.d.run(Unknown Source) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:3e0a6ae:461]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Laurenshup** [comment]
I am not fully sure this has something to do with it. I have looked into the code.
Can you remove the antiProxy.json file, and check if it still shows this error?

**Comment by Dacaly** [comment]
Doing it right now

**Comment by Dacaly** [comment]
The error doesn't occur anymore since I removed antiProxy.json

**Comment by Dacaly** [comment]
```
[12:18:58] [Netty Worker IO Thread #0/INFO]: [_robingames13|/ip:0] <-> ServerConnector [lobby] has disconnected
[12:19:18] [Network Listener - #1/INFO] [Geyser-BungeeCord]: /ip:57769 tried to connect!
[12:19:19] [Network Listener - #0/INFO] [Geyser-BungeeCord]: Player connected with username robingames13
[12:19:19] [defaultEventLoopGroup-4-2/INFO] [Geyser-BungeeCord]: robingames13 (logged in as: robingames13) has connected to the Java server
[12:19:19] [Netty Worker IO Thread #1/INFO] [floodgate]: Floodgate player logged in as _robingames13 joined (UUID: 00000000-0000-0000-0009-01fbfd1597fc)
[12:19:34] [Netty Worker IO Thread #1/INFO]: [/ip:0|_robingames13] <-> DownstreamBridge <-> [lobby] has disconnected
[12:19:35] [Geyser player thread-3-2/WARN] [Geyser-BungeeCord]: Failed to parse message
java.lang.NullPointerException: input
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
```

**Comment by Laurenshup** [comment]
Okay, so it looks like some value was corrupt there. Maybe it was because of a crash of some sort. If it occurs again, I will reopen the issue.

**Comment by Dacaly** [comment]
My antiProxy.json was empty tho

**Comment by Laurenshup** [comment]
Okay, that should not be happening.

**Comment by Laurenshup** [comment]
This issue has now been fixed in the code. There have been added extra checks to make sure BotSentry handles empty files correctly. Will be included in the upcoming version (release before 2022).
