### ISSUE TITLE
null in BackgroundFunction & High CPU usage

### ISSUE THREAD

**Issue by KasprTv** [BlackDemonZyT/BotSentry#66]
[18:14:48] [BotSentry Pool Thread #157/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@5ef0d29e, id=67183, owner=com.lahuca.botsentry.bungee.BotSentryBungee@569deb9a, task=com.lahuca.botsentry.b.b.d@2e293b99, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: null
    at com.lahuca.botsentry.d.b.c.a(Unknown Source) ~[?:?]
    at com.lahuca.botsentry.d.b.c.a(Unknown Source) ~[?:?]
    at com.lahuca.botsentry.b.b.d.run(Unknown Source) ~[?:?]
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[bungee.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:727780a:473]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_275]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_275]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by Laurenshup** [comment]
Same issue with different exception.
`[23:30:06] [BotSentry Pool Thread #44/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@5b40ceb, id=14206, owner=com.lahuca.botsentry.bungee.BotSentryBungee@409bd7cd, task=com.lahuca.botsentry.b.b.d@d91097c, delay=0, period=0, running=true) encountered an exception
java.util.ConcurrentModificationException: null
    at java.util.HashMap$KeySet.forEach(HashMap.java:937) ~[?:1.8.0_312]
    at com.lahuca.botsentry.d.b.c.a(Unknown Source) ~[?:?]
    at com.lahuca.botsentry.d.b.c.a(Unknown Source) ~[?:?]
    at com.lahuca.botsentry.b.b.d.run(Unknown Source) ~[?:?]
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[bungee.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_312]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_312]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] 
`

After investigating it more. It has to do with line 136 in the code. This is for my personal help, so it is not lost anymore.
To cope with this issue and other issues there has to be recoding of some systems.

**Comment by Laurenshup** [comment]
This bug also causes some extra CPU usage. Reloading using /bs reload fixes it temporarily. This is because it will clear the lists.

**Comment by Laurenshup** [comment]
![image](https://user-images.githubusercontent.com/7609330/149527427-24669d63-df78-4ee7-98f1-dda6f304be00.png)
![image](https://user-images.githubusercontent.com/7609330/149527448-c8c30a75-f2ff-42ca-a0b9-af0840c65e71.png)
![image](https://user-images.githubusercontent.com/7609330/149527464-62068750-1b38-471d-824f-4de0a9ebad6d.png)

The first image is the problem. After reloading with /bs reload, the second image is the result of the CPU. The third image is again after a while. Images from customer.

**Comment by Laurenshup** [comment]
A fix of this problem has been deployed to testers. After receiving the results, this issue will be updated.

**Comment by Laurenshup** [comment]
Results show, that the CPU usage has significantly reduced. However, some errors are occuring, which a fix has already been deployed for. Still waiting for test results.

**Comment by Laurenshup** [comment]
After additional testing. All errors have been fully removed. CPU usage stays almost the same. For now, I am closing this issue. In the upcoming version this will be fixed.
