### ISSUE TITLE
Register task while disabled

### ISSUE THREAD

**Issue by Edwin1212256756** [BlackDemonZyT/BotSentry#69]
>....2022-01-16 11:42:06,540 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught org.bukkit.plugin.IllegalPluginAccessException logging ReusableParameterizedMessage: {} lost connection: {} org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552)
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227)
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212)
        at BotSentry-9.3-THANATOS-SpigotMC.jar//com.lahuca.botsentry.spigot.g.a(Unknown Source)
        at BotSentry-9.3-THANATOS-SpigotMC.jar//com.lahuca.botsentry.d.g.a(Unknown Source)
        at BotSentry-9.3-THANATOS-SpigotMC.jar//com.lahuca.botsentry.spigot.a.a.a(Unknown Source)
        at BotSentry-9.3-THANATOS-SpigotMC.jar//com.lahuca.botsentry.spigot.a.a.filter(Unknown Source)
        at org.apache.logging.log4j.core.filter.CompositeFilter.filter(CompositeFilter.java:590)
        at org.apache.logging.log4j.core.filter.AbstractFilterable.isFiltered(AbstractFilterable.java:154)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:482)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2040)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1907)
        at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1449)
        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:1958)
        at net.minecraft.server.network.PlayerConnection.disconnect(PlayerConnection.java:460)
        at net.minecraft.server.players.PlayerList.removeAll(PlayerList.java:1378)
        at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:1063)
        at net.minecraft.server.dedicated.DedicatedServer.stop(DedicatedServer.java:817)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1332)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Laurenshup** [comment]
This issue has been successfully fixed in the upcoming version. It will not try to start any tasks when the server/plugin is shutting down.
