### ISSUE TITLE
BotSentry error on startup

### ISSUE THREAD

**Issue by DarrienNN** [BlackDemonZyT/BotSentry#77]
```java.lang.NullPointerException: Cannot invoke "String.length()" because "this.message" is null
    at me.scarsz.jdaappender.LogItem.clip(LogItem.java:91)
    at me.scarsz.jdaappender.ChannelLoggingHandler.enqueue(ChannelLoggingHandler.java:104)
    at me.scarsz.jdaappender.adapter.Log4JLoggingAdapter.append(Log4JLoggingAdapter.java:61)
    at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
    at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
    at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
    at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
    at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
    at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
    at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1320)
    at com.destroystokyo.paper.console.TerminalConsoleCommandSender.sendRawMessage(TerminalConsoleCommandSender.java:14)
    at org.bukkit.craftbukkit.v1_18_R1.command.CraftConsoleCommandSender.sendMessage(CraftConsoleCommandSender.java:27)
    at com.lahuca.botsentry.spigot.f.a
    at com.lahuca.botsentry.d.a.k.c
    at com.lahuca.botsentry.d.p.b
    at com.lahuca.botsentry.d.p.a
    at com.lahuca.botsentry.b.b.b.a
    at com.lahuca.botsentry.b.b.d.run
    at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
org.apache.logging.log4j.core.appender.AppenderLoggingException: An exception occurred processing Appender JDAAppender
    at org.apache.logging.log4j.core.appender.DefaultErrorHandler.error(DefaultErrorHandler.java:96)
    at org.apache.logging.log4j.core.config.AppenderControl.handleAppenderError(AppenderControl.java:170)
    at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:163)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
    at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
    at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
    at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
    at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
    at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
    at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
    at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
    at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
    at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1320)
    at com.destroystokyo.paper.console.TerminalConsoleCommandSender.sendRawMessage(TerminalConsoleCommandSender.java:14)
    at org.bukkit.craftbukkit.v1_18_R1.command.CraftConsoleCommandSender.sendMessage(CraftConsoleCommandSender.java:27)
    at com.lahuca.botsentry.spigot.f.a
    at com.lahuca.botsentry.d.a.k.c
    at com.lahuca.botsentry.d.p.b
    at com.lahuca.botsentry.d.p.a
    at com.lahuca.botsentry.b.b.b.a
    at com.lahuca.botsentry.b.b.d.run
    at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)```

**Comment by Laurenshup** [comment]
This looks like it is more a problem of the log4j library. Maybe update your Spigot?

**Comment by Laurenshup** [comment]
Due to inactivy, this will be closed.
