### ISSUE TITLE
MySQL executeLargeUpdate not implemented

### ISSUE THREAD

**Issue by ImYenil** [BlackDemonZyT/BotSentry#97]
[22:44:41 INFO]: Lovelyyenil issued server command: /bs scan Lovelyyenil
[22:45:27 WARN]: Exception in thread "Craft Scheduler Thread - 8"
[22:45:27 WARN]: org.apache.commons.lang.UnhandledException: Plugin BotSentry v9.5.2-THANATOS generated an exception while executing task 30
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: executeLargeUpdate not implemented
        at java.sql.Statement.executeLargeUpdate(Unknown Source)
        at com.lahuca.botsentry.e.a.a(Unknown Source)
        at com.lahuca.botsentry.e.c.b(Unknown Source)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by Laurenshup** [comment]
Hmm, this seems to be caused when executeLargeUpdate is unvailable in the MySQL provider. Maybe updating the dependency or MC server version, fixes this?
